import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const root = dirname(fileURLToPath(import.meta.url));

describe("admin UI visual fixtures", () => {
  it("主布局不再使用框架级 overflow-x-hidden", () => {
    const shell = readFileSync(resolve(root, "../../theme/DefaultAdminShell.vue"), "utf8");
    const content = readFileSync(resolve(root, "../../theme/InAdminThemeContent.vue"), "utf8");
    const container = readFileSync(resolve(root, "../container/InContainer.vue"), "utf8");
    const filter = readFileSync(resolve(root, "../container/InSplitLayout.vue"), "utf8");
    expect(shell).not.toContain("overflow-x-hidden");
    expect(content).not.toContain("overflow-x-hidden");
    expect(container).not.toContain("overflow-x-hidden");
    expect(filter).not.toContain("overflow-x-hidden");
    expect(content).toContain("in-content-viewport");
    expect(shell).toContain("has-breadcrumb");
    expect(shell).toContain("has-copyright");
    expect(content).toContain("padding: 0 var(--in-page-gutter);");
    expect(shell).toContain("padding-top: var(--in-page-gutter);");
    expect(content).not.toContain("padding: 0 var(--in-page-gutter) var(--in-page-gutter)");
    expect(shell).toContain("overflow: hidden");
    expect(content).toContain("overflow: hidden");
    expect(shell).toContain("calc(var(--in-sidebar-gutter) + var(--in-sidebar-panel-expanded))");
    expect(shell).toContain("calc(var(--in-sidebar-gutter) + var(--in-sidebar-panel-collapsed))");
    expect(shell).not.toContain("border-right: 1px solid var(--in-border-color)");
    const layoutEntry = readFileSync(resolve(root, "../../layouts/main/IndexPage.vue"), "utf8");
    expect(layoutEntry).toContain("in-admin-theme-layout");
    expect(layoutEntry).not.toContain("in-shell-aside");
    expect(filter).toContain("overflow: hidden");
    const table = readFileSync(resolve(root, "../table/InTable.vue"), "utf8");
    const pageFrame = readFileSync(resolve(root, "../InPageFrame.vue"), "utf8");
    expect(table).not.toContain('aria-label="刷新"');
    expect(table).toContain("tools-start");
    expect(table).toContain("tools-end");
    expect(table).toContain("is-compact");
    expect(table).not.toContain("h(ElTable");
    expect(table).toContain("element-plus/theme-chalk/el-table.css");
    expect(table).toContain("element-plus/theme-chalk/el-checkbox.css");
    expect(table).toContain("--in-table-cell-text");
    expect(table).toContain("--in-table-header-text");
    expect(table).toContain("table-expand-collapsed.svg");
    expect(table).toContain("table-expand-expanded.svg");
    expect(table).toContain(".el-table .cell:has(> .el-table__expand-icon)");
    expect(table).toContain(".el-table__expand-icon),");
    expect(table).toContain("justify-content: center");
    expect(table).toContain("table-checkbox-checked.svg");
    expect(table).toContain("--in-checkbox-radius");
    expect(table).toContain("--in-checkbox-size");
    expect(table).toContain("background-position: center");
    expect(table).toContain("is-custom-tree");
    expect(table).toContain("asCheckboxMode");
    expect(table).toContain("treeColumn");
    expect(table).toContain("InTableTreeCell");
    expect(table).toContain("in-table-tree-cell");
    expect(table).toMatch(/\.in-table__body \{[\s\S]*?overflow: hidden;/);
    expect(table).toContain("showSkeleton");
    expect(table).toContain("in-table-skeleton");
    const tableSkeleton = readFileSync(resolve(root, "../table/InTableSkeleton.vue"), "utf8");
    expect(tableSkeleton).toContain("aria-label=\"加载中\"");
    expect(tableSkeleton).toContain("prefers-reduced-motion");
    expect(table).toContain(".el-table .cell:has(.in-status-tag)");
    expect(table).toContain(":slotted(.in-table__count)");
    expect(table).toContain("gap: var(--in-space-3)");
    expect(pageFrame).toMatch(/\.in-page-frame__body\.is-page \{[\s\S]*?padding-bottom: var\(--in-page-gutter\);/);
    expect(pageFrame).toContain(".in-page-frame__header:has(+ .in-page-frame__tabs)");
    const pageHeader = readFileSync(resolve(root, "../InPageHeader.vue"), "utf8");
    expect(pageHeader).toContain("font-size: var(--in-font-size-section-title)");
    expect(pageHeader).toContain("font-weight: var(--in-font-weight-section-title)");
    expect(pageHeader).toContain("font-weight: var(--in-font-weight-body)");
    expect(pageHeader).toContain("-webkit-line-clamp: 1");
    expect(pageHeader).toContain("word-break: break-all");
    expect(pageHeader).toContain("route.meta.title");
    expect(pageHeader).toContain(
      "M1.293 11.293a1 1 0 0 0 0 1.414l7 7a1 1 0 0 0 1.414-1.414L4.414 13H21a1 1 0 1 0 0-2H4.414l5.293-5.293a1 1 0 0 0-1.414-1.414l-7 7Z",
    );
    expect(pageHeader).toContain("width: 20px");
    expect(pageHeader).toContain("in-page-header__divider");
    expect(pageHeader).not.toContain("ep:back");
    expect(pageHeader).toContain(".in-page-header.has-description {");
    expect(pageHeader).not.toMatch(
      /\.in-page-header \{[^}]*min-height: var\(--in-page-header-min-height\);/,
    );
    expect(pageHeader).toContain(".in-page-header:has(.in-page-header__tabs)");
    const tree = readFileSync(resolve(root, "../InTree.vue"), "utf8");
    expect(tree).toContain("table-expand-collapsed.svg");
    expect(tree).toContain("table-expand-expanded.svg");
    expect(tree).toContain(".el-tree-node__content");
    expect(tree).toContain(".el-tree-node__label");
    expect(tree).toContain("align-items: center");
    expect(tree).toContain(".el-tree-node__expand-icon.expanded::before");
    expect(tree).toContain(".el-tree-node__expand-icon.is-leaf::before");
    expect(tree).toContain("line-height: 0");
    expect(tree).toContain("transform: none !important");
    const avatar = readFileSync(resolve(root, "../avatar/InAvatar.vue"), "utf8");
    expect(avatar).toContain("width: var(--in-avatar-size)");
    expect(avatar).toContain("border-radius: 50%");
    expect(avatar).toContain("showAvatar");
    expect(avatar).toContain("showName");
    const bizTabs = readFileSync(resolve(root, "../tabs/InBizTabsHeader.vue"), "utf8");
    expect(bizTabs).toContain("in-biz-tabs-ink");
    expect(bizTabs).toContain("height: calc(var(--in-biz-tabs-ink-height) * 2)");
    expect(bizTabs).toContain("border-radius: var(--in-biz-tabs-ink-height)");
    expect(bizTabs).toContain("overflow: hidden");
    expect(bizTabs).toContain('querySelector(".inner")');
    expect(bizTabs).toContain("font-size: var(--in-biz-tabs-font-size)");
    expect(bizTabs).toContain("var(--in-biz-tabs-ink-ease)");
    const dropdownCss = readFileSync(resolve(root, "../../styles/dropdown.css"), "utf8");
    expect(dropdownCss).toContain(".el-dropdown__popper.el-popper");
    expect(dropdownCss).toContain("align-items: center");
    expect(dropdownCss).toContain("gap: var(--in-space-2)");
    expect(dropdownCss).toContain("line-height: var(--in-line-height-body)");
    expect(dropdownCss).toContain(":focus-visible");
    expect(dropdownCss).toContain("border: 1px solid var(--in-border-color)");
    expect(dropdownCss).toContain("border-radius: var(--in-radius-control)");
    expect(dropdownCss).toContain("box-shadow: var(--in-shadow-overlay)");
    expect(dropdownCss).toContain("color: var(--in-text-color)");
    expect(dropdownCss).toContain(".el-popper__arrow");
    expect(dropdownCss).toContain("display: none");
    expect(dropdownCss).toContain(".el-dropdown__popper .el-dropdown-menu__item--divided");
    expect(dropdownCss).toContain(".in-user-dropdown__divider");
    const tooltipCss = readFileSync(resolve(root, "../../styles/tooltip.css"), "utf8");
    expect(tooltipCss).toContain(".el-popper.is-dark");
    expect(tooltipCss).toContain("background: var(--in-text-color)");
    expect(tooltipCss).toContain("color: var(--in-text-color-inverse)");
    expect(tooltipCss).toContain("border-radius: var(--in-radius-control)");
    expect(tooltipCss).toContain(".el-popper__arrow::before");
    const userDropdown = readFileSync(
      resolve(root, "../../layouts/widgets/user-dropdown/InUserDropdown.vue"),
      "utf8",
    );
    expect(userDropdown).toContain("in-user-dropdown__divider");
    expect(userDropdown).toContain("user-dropdown-header-divider");
    expect(userDropdown).not.toContain("divided disabled");
    expect(userDropdown).toContain("FixPwdDialog");
    expect(userDropdown).not.toContain("FixPwdDrawer");
    const drawer = readFileSync(resolve(root, "../drawer/InDrawer.vue"), "utf8");
    expect(drawer).toContain("in-drawer-overlay");
    expect(drawer).toContain("background-color: var(--in-drawer-overlay, transparent)");
    expect(drawer).toContain("--el-overlay-color-lighter: transparent");
    expect(drawer).toContain("overlayColor");
    expect(drawer).toContain("InLoading");
    expect(drawer).not.toContain("v-loading");
    const confirmCss = readFileSync(resolve(root, "../../styles/confirm-dialog.css"), "utf8");
    expect(confirmCss).toContain(".in-confirm-dialog");
    expect(confirmCss).toContain(".in-confirm-dialog-overlay .el-overlay-message-box");
    expect(confirmCss).toContain(".el-overlay:has(.in-dialog)");
    expect(confirmCss).toContain("display: inline-flex");
    expect(confirmCss).toContain("align-items: center");
    expect(confirmCss).toContain("justify-content: center");
    expect(confirmCss).toContain("in-confirm-dialog__texts");
    expect(confirmCss).toContain("in-confirm-dialog.is-closable");
    expect(confirmCss).toContain("in-confirm-dialog__content");
    expect(confirmCss).toContain("border-radius: var(--in-radius-card)");
    expect(confirmCss).toContain("color: var(--in-text-color)");
    const messageCss = readFileSync(resolve(root, "../../styles/message.css"), "utf8");
    expect(messageCss).toContain(".el-message.in-message");
    expect(messageCss).toContain("min-width: var(--in-message-min-width)");
    expect(messageCss).toContain("height: var(--in-message-height)");
    expect(messageCss).toContain("flex-shrink: 0");
    expect(messageCss).toContain("white-space: nowrap");
    expect(messageCss).toContain("border-radius: var(--in-radius-control)");
    expect(messageCss).toContain("box-shadow: var(--in-shadow-overlay)");
    expect(messageCss).toContain("color: var(--in-text-color)");
    expect(messageCss).toContain("el-message--success");
    expect(messageCss).toContain("el-message--warning");
    const stylesIndex = readFileSync(resolve(root, "../../styles/index.ts"), "utf8");
    expect(stylesIndex).toContain('import "./message.css"');
    expect(stylesIndex).toContain('import "./tooltip.css"');
    expect(stylesIndex).toContain('import "element-plus/theme-chalk/el-button.css"');
    expect(stylesIndex).toContain('import "./button.css"');
    const buttonCss = readFileSync(resolve(root, "../../styles/button.css"), "utf8");
    expect(buttonCss).toContain(".el-button.is-plain.el-button--primary");
    expect(buttonCss).toContain(".el-button.is-plain.el-button--danger");
    expect(buttonCss).toContain(".el-button.is-plain.el-button--warning");
    expect(buttonCss).toContain("--el-button-bg-color: var(--in-bg-color-surface)");
    expect(buttonCss).toContain("--el-button-hover-bg-color: var(--in-button-plain-color)");
    expect(buttonCss).toContain("--el-button-hover-text-color: var(--in-text-color-inverse)");
    expect(buttonCss).toContain("--el-button-text-color: var(--in-button-plain-color)");
    expect(buttonCss).toContain("--el-button-border-color: var(--in-button-plain-color)");
    expect(buttonCss).toContain("--in-button-plain-color: var(--in-color-primary)");
    expect(buttonCss).toContain("--in-button-plain-color: var(--in-color-danger)");
    expect(buttonCss).toContain("--in-button-plain-color: var(--in-color-warning)");
    const dialog = readFileSync(resolve(root, "../InDialog.vue"), "utf8");
    expect(dialog).toContain("align-center");
    expect(dialog).toContain("showClose");
    expect(dialog).toContain("in-dialog__icon");
    expect(dialog).toContain("name=\"icon\"");
    expect(dialog).toContain("& .el-dialog__body");
    expect(dialog.match(/padding: var\(--in-space-4\) var\(--in-section-padding-relaxed\)/g)).toHaveLength(
      2,
    );
    expect(dialog).toContain("& .el-form-item:last-child");
    const detailDrawer = readFileSync(resolve(root, "../drawer/InDetailDrawer.vue"), "utf8");
    expect(detailDrawer).toContain('layout="pinned"');
    expect(detailDrawer).toContain("编辑");
    const statusTag = readFileSync(resolve(root, "../status/StatusTag.vue"), "utf8");
    const commonStatusTag = readFileSync(resolve(root, "../status/InCommonStatusTag.vue"), "utf8");
    const accountStatus = readFileSync(resolve(root, "../status/InAccountStatusTag.vue"), "utf8");
    expect(statusTag).toContain("in-status-tag");
    expect(statusTag).toContain("width: max-content");
    expect(statusTag).not.toContain("text-overflow: ellipsis");
    expect(statusTag).toContain("--in-status-tag-info-color");
    expect(statusTag).toContain("--in-status-tag-warning-color");
    expect(statusTag).toContain("--in-status-tag-danger-color");
    expect(commonStatusTag).toContain("已暂停");
    expect(commonStatusTag).not.toContain("已锁定");
    expect(accountStatus).toContain("已暂停");
    expect(accountStatus).toContain("已锁定");
  });

  it("顶栏与侧栏尺寸 Token 已对齐验收值", () => {
    const tokens = readFileSync(resolve(root, "../../styles/tokens.css"), "utf8");
    expect(tokens).toContain("--in-app-bar-height: 56px");
    expect(tokens).toContain("--in-app-bar-nav-max: 560px");
    expect(tokens).toContain("--in-app-bar-actions-max: 360px");
    expect(tokens).toContain("--in-app-bar-search-width: 400px");
    expect(tokens).toContain("--in-sidebar-panel-expanded: 236px");
    expect(tokens).toContain("--in-sidebar-panel-collapsed: 52px");
    expect(tokens).toContain("--in-sidebar-gutter: 8px");
    expect(tokens).toContain("--in-split-left-width: 260px");
    expect(tokens).toContain("--in-table-header-height: 48px");
    expect(tokens).toContain("--in-control-height: 32px");
    expect(tokens).toContain("--in-bg-color-canvas");
    expect(tokens).toContain("--in-bg-color-sidebar");
    expect(tokens).toContain("--in-bg-color-surface");
    expect(tokens).toContain("--in-container-radius: 0px");
    expect(tokens).toContain("--in-container-bg: var(--in-bg-color-surface)");
    expect(tokens).toContain("--in-split-rail-width: 0px");
    expect(tokens).toContain("--in-split-collapse-width: 16px");
    expect(tokens).toContain("--in-split-collapse-height: 32px");
    expect(tokens).toContain("--in-split-collapse-radius: 8px");
    expect(tokens).toContain("--in-table-row-height-compact: 44px");
    expect(tokens).toContain("--in-motion-duration-split: 180ms");
    expect(tokens).toContain("--in-bg-color-subtle: #fbfbfb");
    expect(tokens).toContain("--in-motion-ease-sidebar: cubic-bezier(0.25, 0.1, 0.05, 1)");
    expect(tokens).toContain("--in-menu-icon-size: 20px");
    expect(tokens).toContain("--in-menu-icon-gap: var(--in-space-2)");
    expect(tokens).toContain("--in-menu-base-level-padding: 16px");
    expect(tokens).toContain("--in-menu-nested-indent: var(--in-space-5)");
    expect(tokens).toContain("--in-menu-text-plain-color: var(--in-text-color)");
    expect(tokens).toContain("--in-menu-text-active-color: var(--in-gray-900)");
    expect(tokens).toContain("--in-gray-900: #2b2f36");
    expect(tokens).toContain("--in-menu-item-height: 40px");
    expect(tokens).toContain("--in-menu-footer-clearance: 18px");
    expect(tokens).toContain("--in-menu-divider-gap: var(--in-space-2)");
    expect(tokens).toContain("--in-menu-control-height: 44px");
    expect(tokens).toContain("--in-bg-color-menu-hover: rgba(31, 35, 41, 0.06)");
    expect(tokens).toContain("--in-bg-color-control-hover: rgba(31, 35, 41, 0.08)");
    expect(tokens).toContain("--in-biz-tabs-font-size: var(--in-font-size-section-title)");
    expect(tokens).toContain("--in-biz-tabs-ink-height: 3px");
    expect(tokens).toContain("--in-motion-ease-tabs-ink: cubic-bezier(0.34, 0.69, 0.1, 1)");
    expect(tokens).toContain("--in-avatar-size-lg: 48px");
    expect(tokens).toContain("--in-drawer-width-detail: 480px");
    expect(tokens).toContain("--in-table-cell-text: #18263c");
    expect(tokens).toContain("--in-table-header-text: var(--in-text-color-secondary)");
    expect(tokens).toContain("--in-checkbox-radius: 4px");
    expect(tokens).toContain("--in-checkbox-size: 16px");
    expect(tokens).toContain("--in-message-min-width: 204px");
    expect(tokens).toContain("--in-message-height: 54px");
    expect(tokens).toContain("--in-message-icon-size: 20px");
  });

  it("容器默认直角无边框，双栏折叠带宽度过渡", () => {
    const container = readFileSync(resolve(root, "../container/InContainer.vue"), "utf8");
    const filter = readFileSync(resolve(root, "../container/InSplitLayout.vue"), "utf8");
    expect(container).toContain("variant: \"plain\"");
    expect(container).toContain("background: var(--in-container-bg)");
    expect(container).toContain("border-radius: var(--in-container-radius)");
    expect(container).toContain("--in-container-bg: transparent");
    expect(container).toContain("borderColor");
    expect(filter).toContain("leftCollapsible: true");
    expect(filter).toContain("autoCollapse: true");
    expect(filter).toContain("minRightWidth: 680");
    expect(filter).toContain("width var(--in-motion-duration-split)");
    expect(filter).toContain("left var(--in-motion-duration-split)");
    expect(filter).toContain("translate(-1px, -50%)");
    expect(filter).toContain("border-left: 0");
    expect(filter).toContain("padding: var(--in-section-padding)");
    expect(filter).toContain("gap: var(--in-space-3)");
    expect(filter).toContain("var(--in-split-left-bg, var(--in-container-bg))");
    expect(filter).toContain("leftBackground");
  });

  it("侧栏滚动视口与底部控制分离，无 collapse popper", () => {
    const menu = readFileSync(resolve(root, "../../layouts/widgets/InMenu.vue"), "utf8");
    const layout = readFileSync(resolve(root, "../../theme/DefaultAdminShell.vue"), "utf8");
    const toggle = readFileSync(resolve(root, "../../layouts/widgets/InMenuToggle.vue"), "utf8");
    expect(menu).toContain("in-menu__scroll");
    expect(menu).toContain("in-menu__control");
    expect(menu).toContain(".el-scrollbar__bar");
    expect(menu).toContain("scrollbar-width: none");
    expect(menu.replace(/\s+/g, " ")).toContain(
      "grid-template-rows: minmax(0, 1fr) var(--in-menu-footer-clearance) 1px var(--in-menu-divider-gap) var(--in-menu-control-height) var(--in-sidebar-gutter)",
    );
    expect(menu).toContain("in-menu__divider");
    expect(menu).toContain("in-menu__divider-gap");
    expect(menu).toContain("select-none");
    expect(menu).toContain("user-select: none");
    expect(menu).toContain(':collapse="false"');
    expect(menu).toContain("收起导航");
    expect(menu).toContain("展开导航");
    expect(menu).toContain("ic_close");
    expect(menu).toContain("ic_expand");
    expect(menu).toContain("padding: 0 var(--in-menu-base-level-padding)");
    expect(menu).not.toContain("ep:arrow-left");
    expect(menu).not.toContain("ep:arrow-right");
    expect(menu).not.toContain("收起菜单");
    expect(menu).toContain("--in-menu-nested-indent");
    expect(menu).toContain("in-menu-node.has-icon");
    const submenu = readFileSync(resolve(root, "../../layouts/widgets/InSubmenu.vue"), "utf8");
    expect(submenu).toContain("in-menu-node__icon");
    expect(submenu).toContain("v-if=\"itemIcon\"");
    expect(submenu).toContain("--in-menu-depth");
    expect(layout).toContain("padding-left: var(--in-sidebar-gutter)");
    expect(layout).toContain("var(--in-motion-ease-sidebar)");
    expect(toggle).toContain("v-if=\"isOverlay\"");
    expect(toggle).toContain("关闭导航");
  });

  it("顶栏按品牌/导航/搜索/小部件/用户五区划分", () => {
    const bar = readFileSync(resolve(root, "../../layouts/widgets/InAppBar.vue"), "utf8");
    const search = readFileSync(resolve(root, "../../layouts/widgets/search/InAppBarSearch.vue"), "utf8");
    const logo = readFileSync(resolve(root, "../../layouts/widgets/InLogo.vue"), "utf8");
    expect(bar).toContain("in-app-bar-brand");
    expect(bar).toContain("in-app-bar-nav");
    const nav = readFileSync(resolve(root, "../../layouts/widgets/header/InAppBarNav.vue"), "utf8");
    expect(nav).toContain("color: var(--in-text-color)");
    expect(nav).toContain("gap: 6px");
    expect(nav).toContain("font-size: var(--in-app-bar-icon-size)");
    expect(nav).toContain("font-weight: var(--in-font-weight-body)");
    expect(nav).toContain("font-weight: var(--in-font-weight-section-title)");
    expect(nav).toContain("padding: 7px var(--in-space-3)");
    expect(nav).toContain("margin: 0 var(--in-space-6) 0 0");
    expect(nav).toContain("border-radius: var(--in-radius-card)");
    expect(nav).toContain("line-height: var(--in-line-height-body)");
    expect(nav).toContain("color-mix(in srgb, var(--in-text-color) 6%, transparent)");
    expect(nav).toContain("in-app-bar-overlay--nav");
    expect(nav).toContain("in-app-bar-nav-panel__title");
    expect(nav).toContain("border-bottom: 1px solid var(--in-border-color)");
    expect(nav).toContain("grid-auto-flow: column");
    expect(nav).toContain("in-app-bar-nav-panel__label");
    expect(nav).toContain("height: 42px");
    expect(nav).toContain("in-app-bar-nav__caret");
    expect(nav).toContain(".in-app-bar-nav__caret svg");
    expect(nav).toContain("width: 12px");
    expect(nav).toContain("transition: transform var(--in-motion-duration) var(--in-motion-ease)");
    expect(nav).toContain("prefers-reduced-motion");
    expect(nav).toContain("width: max-content");
    expect(nav).toContain("overflow-x: hidden");
    expect(nav).toContain("overflow-y: auto");
    expect(bar).toContain("in-app-bar-search-pane");
    expect(bar).toContain("in-app-bar-utilities");
    expect(bar).toContain("in-app-bar__user");
    expect(bar).toContain("in-app-bar__divider");
    const fullscreen = readFileSync(
      resolve(root, "../../layouts/widgets/InFullscreen.vue"),
      "utf8",
    );
    expect(fullscreen).toContain("bi:fullscreen");
    expect(fullscreen).toContain("bi:fullscreen-exit");
    const utilities = readFileSync(
      resolve(root, "../../layouts/widgets/header/InAppBarUtilities.vue"),
      "utf8",
    );
    expect(utilities).toContain("in-app-bar-utilities__icon-wrap");
    expect(utilities).toContain("min-width: 14px");
    expect(utilities).toContain("height: 14px");
    expect(utilities).toContain("transform: translate(40%, -40%)");
    const mainCss = readFileSync(resolve(root, "../../styles/main.css"), "utf8");
    expect(mainCss).toContain(".in-icon {");
    expect(mainCss).toContain(".in-icon svg");
    expect(mainCss).toMatch(/\.in-icon \{[\s\S]*?width: 1em;/);
    expect(mainCss).toContain(".in-app-bar__icon");
    expect(mainCss).toContain("color: var(--in-text-color-secondary)");
    expect(mainCss).toContain("text-rendering: optimizeLegibility");
    expect(mainCss).toContain("-webkit-font-smoothing: antialiased");
    expect(bar).not.toContain("max-width: var(--in-app-bar-nav-max)");
    expect(bar).not.toContain("overflow-x: auto");
    expect(search).toContain("var(--in-app-bar-search-width)");
    expect(logo).toContain("resolveAppBarLogo");
    expect(logo).toContain("useAdminTheme");
    const logoResolver = readFileSync(resolve(root, "../../layouts/widgets/resolveAppBarLogo.ts"), "utf8");
    expect(logoResolver).toContain("in-light-framed.svg");
    expect(logoResolver).toContain("in-dark-framed.svg");
  });

  it("全局加载使用明暗主题 SVG 动画", () => {
    const loading = readFileSync(resolve(root, "../InGlobalLoading.vue"), "utf8");
    const mark = readFileSync(resolve(root, "../InLoadingMark.vue"), "utf8");
    const local = readFileSync(resolve(root, "../InLoading.vue"), "utf8");
    expect(loading).toContain("name: \"InGlobalLoading\"");
    expect(loading).toContain("InLoadingMark");
    expect(loading).toContain("var(--in-bg-color-canvas)");
    expect(loading).toContain("in-global-loading-dots");
    expect(mark).toContain("in-loading-light.svg");
    expect(mark).toContain("in-loading-dark.svg");
    expect(mark).toContain("useAdminTheme");
    expect(local).toContain("background: transparent");
    expect(local).not.toContain("el-loading");
    expect(loading).toContain("prefers-reduced-motion");
    expect(loading).not.toContain("in-global-loading-box-item");
    expect(loading).not.toContain("in-global-loading-animation");
    const searchPanel = readFileSync(
      resolve(root, "../../layouts/widgets/search/InAppBarSearchPanel.vue"),
      "utf8",
    );
    expect(searchPanel).toContain("InLoadingMark");
    expect(searchPanel).not.toContain("is-loading");
    expect(searchPanel).toContain("in-app-bar-search-panel__clear");
    expect(searchPanel).toContain("font-size: 16px");
  });

  it("InTableActions 直出按钮启用态有 hover，禁用态不响应", () => {
    const actions = readFileSync(resolve(root, "../table/InTableActions.vue"), "utf8");
    expect(actions).toContain(".in-table-actions__inline:hover:not(:disabled)");
    expect(actions).toContain(".in-table-actions__inline.is-toolbar:hover:not(:disabled)");
    expect(actions).toContain(".in-table-actions__inline.is-toolbar.is-primary:hover:not(:disabled)");
    expect(actions).toContain(".in-table-actions__inline.is-toolbar.is-danger:hover:not(:disabled)");
    expect(actions).toContain(".in-table-actions__inline.is-toolbar.is-filled:hover:not(:disabled)");
    expect(actions).toContain("padding: var(--in-space-1)");
    expect(actions).toContain(".in-table-actions__item.is-active:not(.is-disabled)");
    expect(actions).toContain("activeIndex.value = focusFirst ? 0 : -1");
  });

  it("InFilterPanel 为工具栏筛选浮层：文案筛选、32px 描边、Teleport、角标", () => {
    const panel = readFileSync(resolve(root, "../table/InFilterPanel.vue"), "utf8");
    expect(panel).toContain("name: \"InFilterPanel\"");
    expect(panel).toContain("aria-label=\"筛选条件\"");
    expect(panel).toContain("筛选");
    expect(panel).not.toContain("更多");
    expect(panel).toContain("Teleport to=\"body\"");
    expect(panel).toContain("in-filter-panel__badge");
    expect(panel).toContain("height: var(--in-control-height)");
    expect(panel).toContain("activeCount");
    expect(panel).toContain("Escape");
    expect(panel).toContain("z-index: var(--in-z-dropdown)");
  });

  it("InPicker 为紧凑单选：可选 label、32px 触发器、相邻 12px", () => {
    const picker = readFileSync(resolve(root, "../select/InPicker.vue"), "utf8");
    expect(picker).toContain("name: \"InPicker\"");
    expect(picker).toContain("in-picker__label");
    expect(picker).toContain("height: var(--in-control-height)");
    expect(picker).toContain("border: 1px solid #d0d3d6");
    expect(picker).toContain(".in-picker__trigger:hover:not(:disabled)");
    expect(picker).toContain("color: var(--in-text-color-placeholder)");
    expect(picker).toContain("color: var(--in-color-primary)");
    expect(picker).toContain("in-picker__check");
    expect(picker).toContain(".in-picker + .in-picker");
    expect(picker).toContain("margin-inline-start: var(--in-space-3)");
    expect(picker).toContain("Teleport to=\"body\"");
    expect(picker).toContain(
      "M4 11.293a1 1 0 0 1 1.414 0l4.072 4.07 9.07-9.07a1 1 0 0 1 1.415 0l.706.707a1 1 0 0 1 0 1.414L10.193 18.9a1 1 0 0 1-1.415 0l-5.485-5.485a1 1 0 0 1 0-1.414L4 11.293Z",
    );
  });
});
