/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChallengeHost: typeof import('./src/components/challenge/ChallengeHost.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    InButton: typeof import('./src/components/InButton.vue')['default']
    InContainer: typeof import('./src/components/container/InContainer.vue')['default']
    InCopyTag: typeof import('./src/components/InCopyTag.vue')['default']
    InDialog: typeof import('./src/components/InDialog.vue')['default']
    InFilterItem: typeof import('./src/components/container/InFilterItem.vue')['default']
    InIcon: typeof import('./src/components/InIcon.vue')['default']
    InLoading: typeof import('./src/components/InLoading.vue')['default']
    InQrcode: typeof import('./src/components/qrcode/InQrcode.vue')['default']
    InSplitLayout: typeof import('./src/components/container/InSplitLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Verify: typeof import('./src/components/verifition/Verify.vue')['default']
    VerifyPoints: typeof import('./src/components/verifition/verify/VerifyPoints.vue')['default']
    VerifySlide: typeof import('./src/components/verifition/verify/VerifySlide.vue')['default']
  }
}
