/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountStatusEditButton: typeof import('./src/components/biz/user/AccountStatusEditButton.vue')['default']
    AccountStatusView: typeof import('./src/components/biz/user/AccountStatusView.vue')['default']
    BizDeptSelect: typeof import('./src/components/biz/dept-select/BizDeptSelect.vue')['default']
    BizSearchUserByPhone: typeof import('./src/components/biz/search-user-by-phone/BizSearchUserByPhone.vue')['default']
    ClientSelect: typeof import('./src/components/biz/ClientSelect.vue')['default']
    CommonStatusButton: typeof import('./src/components/biz/CommonStatusButton.vue')['default']
    CommonStatusTag: typeof import('./src/components/biz/CommonStatusTag.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElInputTag: typeof import('element-plus/es')['ElInputTag']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    'ICarbon:listBoxes': typeof import('~icons/carbon/list-boxes')['default']
    'ICarbon:parentChild': typeof import('~icons/carbon/parent-child')['default']
    'IEp:arrowLeft': typeof import('~icons/ep/arrow-left')['default']
    'IEp:delete': typeof import('~icons/ep/delete')['default']
    'IEp:edit': typeof import('~icons/ep/edit')['default']
    'IEp:plus': typeof import('~icons/ep/plus')['default']
    'IMaterialSymbols:expandRounded': typeof import('~icons/material-symbols/expand-rounded')['default']
    'IMaterialSymbols:moreVert': typeof import('~icons/material-symbols/more-vert')['default']
    'IMdi:arrowVerticalCollapse': typeof import('~icons/mdi/arrow-vertical-collapse')['default']
    'IMdi:cardAccountDetailsOutline': typeof import('~icons/mdi/card-account-details-outline')['default']
    InInputTag: typeof import('./src/components/biz/InInputTag.vue')['default']
    InStatusButton: typeof import('./src/components/biz/InStatusButton.vue')['default']
    InTag: typeof import('./src/components/biz/InTag.vue')['default']
    InTagEnum: typeof import('./src/components/biz/InTagEnum.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TenantOptions: typeof import('./src/components/biz/tenant-options/TenantOptions.vue')['default']
    TenantSelect: typeof import('./src/components/biz/TenantSelect.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
