/** 与 packages/admin-core/src/theme/tokens.ts 保持同步，测试会核对。 */
export const IN_THEME_TOKEN_NAMES = [
  "--in-blue-500",
  "--in-blue-600",
  "--in-blue-400",
  "--in-gray-950",
  "--in-gray-900",
  "--in-gray-700",
  "--in-gray-500",
  "--in-gray-400",
  "--in-gray-300",
  "--in-gray-200",
  "--in-gray-100",
  "--in-white",
  "--in-black",
  "--in-danger-500",
  "--in-success-500",
  "--in-warning-500",
  "--in-warning-600",
  "--in-info-500",
  "--in-space-1",
  "--in-space-2",
  "--in-space-3",
  "--in-space-4",
  "--in-space-5",
  "--in-space-6",
  "--in-space-8",
  "--in-radius-control",
  "--in-radius-card",
  "--in-radius-card-lg",
  "--in-font-size-page-title",
  "--in-line-height-page-title",
  "--in-font-weight-page-title",
  "--in-font-size-section-title",
  "--in-line-height-section-title",
  "--in-font-weight-section-title",
  "--in-font-size-body",
  "--in-line-height-body",
  "--in-font-weight-body",
  "--in-font-size-caption",
  "--in-line-height-caption",
  "--in-shadow-none",
  "--in-shadow-sm",
  "--in-shadow-md",
  "--in-shadow-overlay",
  "--in-z-header",
  "--in-z-sidebar",
  "--in-z-overlay-mask",
  "--in-z-overlay-sidebar",
  "--in-z-dropdown",
  "--in-motion-duration",
  "--in-motion-duration-sidebar",
  "--in-motion-duration-split",
  "--in-motion-duration-tabs-ink",
  "--in-motion-ease",
  "--in-motion-ease-sidebar",
  "--in-motion-ease-tabs-ink",
  "--in-color-primary",
  "--in-color-success",
  "--in-color-warning",
  "--in-color-danger",
  "--in-color-info",
  "--in-text-color",
  "--in-text-color-secondary",
  "--in-text-color-placeholder",
  "--in-text-color-disabled",
  "--in-text-color-inverse",
  "--in-bg-color-canvas",
  "--in-bg-color-sidebar",
  "--in-bg-color-surface",
  "--in-bg-color-muted",
  "--in-bg-color-subtle",
  "--in-bg-color",
  "--in-bg-color-page",
  "--in-bg-color-mute",
  "--in-bg-color-hover",
  "--in-bg-color-active",
  "--in-bg-color-menu-hover",
  "--in-bg-color-control-hover",
  "--in-border-color",
  "--in-border-color-light",
  "--in-focus-ring-color",
  "--in-overlay-mask",
  "--in-app-bar-height",
  "--in-app-bar-padding-inline",
  "--in-app-bar-padding",
  "--in-app-bar-icon-size",
  "--in-app-bar-nav-max",
  "--in-app-bar-actions-max",
  "--in-app-bar-search-width",
  "--in-app-bar-bg",
  "--in-app-bar-text",
  "--in-app-bar-border",
  "--in-icon-button-size",
  "--in-sidebar-gutter",
  "--in-sidebar-panel-expanded",
  "--in-sidebar-panel-collapsed",
  "--in-menu-show",
  "--in-menu-hide",
  "--in-menu-item-height",
  "--in-menu-item-radius",
  "--in-menu-item-gap",
  "--in-menu-content-padding-top",
  "--in-menu-footer-clearance",
  "--in-menu-divider-gap",
  "--in-menu-control-height",
  "--in-menu-control-radius",
  "--in-menu-icon-size",
  "--in-menu-icon-gap",
  "--in-menu-base-level-padding",
  "--in-menu-level-padding",
  "--in-menu-nested-indent",
  "--in-menu-line-height",
  "--in-menu-bg-color",
  "--in-menu-bg-hover-color",
  "--in-menu-text-color",
  "--in-menu-text-plain-color",
  "--in-menu-text-active-color",
  "--in-menu-item-font-size",
  "--in-menu-item-font-weight",
  "--in-menu-item-font-weight-active",
  "--in-container-bg",
  "--in-container-radius",
  "--in-container-border-width",
  "--in-container-border-color",
  "--in-split-left-width",
  "--in-split-rail-width",
  "--in-split-collapse-width",
  "--in-split-collapse-height",
  "--in-split-collapse-radius",
  "--in-split-header-min-height",
  "--in-split-header-padding",
  "--in-control-height",
  "--in-control-height-small",
  "--in-table-header-height",
  "--in-table-row-height",
  "--in-table-row-height-compact",
  "--in-table-header-bg",
  "--in-table-header-text",
  "--in-table-cell-text",
  "--in-checkbox-radius",
  "--in-checkbox-size",
  "--in-message-min-width",
  "--in-message-height",
  "--in-message-icon-size",
  "--in-breadcrumb-icon-size",
  "--in-breadcrumb-height",
  "--in-page-breadcrumb-height",
  "--in-page-header-min-height",
  "--in-avatar-size",
  "--in-avatar-size-lg",
  "--in-status-tag-height",
  "--in-status-tag-radius",
  "--in-status-tag-info-color",
  "--in-status-tag-info-bg",
  "--in-status-tag-warning-color",
  "--in-status-tag-warning-bg",
  "--in-status-tag-danger-color",
  "--in-status-tag-danger-bg",
  "--in-copyright-height",
  "--in-biz-tabs-font-size",
  "--in-biz-tabs-color",
  "--in-biz-tabs-color-active",
  "--in-biz-tabs-ink-height",
  "--in-biz-tabs-ink-duration",
  "--in-biz-tabs-ink-ease",
  "--in-drawer-width-detail",
  "--in-page-gutter",
  "--in-section-padding",
  "--in-section-padding-relaxed",
  "--in-text-color-light",
  "--in-text-color-lighter",
  "--in-text-color-primary",
  "--in-common-margin",
  "--in-common-padding",
  "--in-common-border-radius",
  "--in-common-title-color",
  "--in-common-title-font-weight",
  "--in-common-title-font-size",
  "--in-box-shadow",
  "--in-color-info-light-5",
  "--in-border-style",
  "--in-transition-duration",
];

export const HEADER_BUILTIN_UTILITIES = ["fullscreen", "settings"];
export const HEADER_BUILTIN_USER_MENU = ["switchOrg", "fixPwd", "logout"];
export const COMPONENT_SIZES = ["default", "small", "large"];
export const THEME_PARTS = ["header", "navigation", "breadcrumb", "footer"];

export const BUILTIN_ENV_FIELDS = [
  {
    key: "VITE_APP_CODE",
    group: "identity",
    label: "应用编码",
    control: "string",
    required: true,
    output: "env",
    docs: "/guide/app-config.html#环境变量",
    consumed: true,
  },
  {
    key: "VITE_APP_TITLE",
    group: "identity",
    label: "标题",
    control: "string",
    required: true,
    output: "env",
    docs: "/guide/app-config.html#环境变量",
    consumed: true,
  },
  {
    key: "VITE_APP_SYMBOL",
    group: "identity",
    label: "框架标识",
    control: "string",
    required: true,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_COPYRIGHT",
    group: "identity",
    label: "版权",
    control: "string",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_LOGIN_URI",
    group: "login",
    label: "登录地址",
    control: "url",
    required: true,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_LOGIN_CALLBACK_URI",
    group: "login",
    label: "登录回调",
    control: "url",
    required: true,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_ERROR_IMAGE",
    group: "login",
    label: "错误页图片",
    control: "string",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_FINGERPRINT_ENABLED",
    group: "login",
    label: "设备指纹",
    control: "boolean",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_NET_BASE_URL",
    group: "network",
    label: "接口基址",
    control: "string",
    required: false,
    output: "env",
    hint: "省略时沿用运行时默认，不在公共文件中强制写出",
    consumed: true,
  },
  {
    key: "VITE_APP_NET_DEFAULT_TIMEOUT",
    group: "network",
    label: "请求超时（毫秒）",
    control: "integer",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_NET_DEFAULT_TIMEOUT_MESSAGE",
    group: "network",
    label: "超时提示",
    control: "string",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_STORE_PREFIX",
    group: "storage",
    label: "存储前缀",
    control: "string",
    required: true,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_COOKIE_DOMAIN",
    group: "storage",
    label: "Cookie 域",
    control: "string",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_COOKIE_DEFAULT_EXPIRE_TIME",
    group: "storage",
    label: "Cookie 过期（秒）",
    control: "integer",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_SETTINGS_COMPONENT_SIZE",
    group: "ui",
    label: "组件尺寸",
    control: "enum",
    options: COMPONENT_SIZES,
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_SETTINGS_SHOW_MENU",
    group: "ui",
    label: "显示菜单",
    control: "boolean",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_SETTINGS_SHOW_BREADCRUMB",
    group: "ui",
    label: "显示面包屑",
    control: "boolean",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_SETTINGS_SHOW_COPYRIGHT",
    group: "ui",
    label: "显示版权",
    control: "boolean",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_SETTINGS_SHOW_SEARCH",
    group: "ui",
    label: "显示搜索",
    control: "boolean",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_SETTINGS_SHOW_WATERMARK",
    group: "ui",
    label: "显示水印",
    control: "boolean",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_BASIC_TOKEN",
    group: "request",
    label: "Basic Token",
    control: "string",
    required: false,
    output: "env",
    hint: "浏览器构建变量可被客户端读取",
    consumed: true,
  },
  {
    key: "VITE_APP_BUCKET_NAME",
    group: "request",
    label: "存储桶",
    control: "string",
    required: false,
    output: "env",
    consumed: true,
  },
  {
    key: "VITE_APP_TENANT",
    group: "legacy",
    label: "租户（遗留）",
    control: "string",
    required: false,
    output: "custom-only",
    hint: "现有模板存在而入口未消费；默认不输出。显式填写时作为自定义变量保留，不改变租户行为。",
    consumed: false,
  },
];

export const BUILTIN_ENV_KEYS = BUILTIN_ENV_FIELDS.filter((field) => field.consumed).map(
  (field) => field.key,
);

export const REQUIRED_ENV_KEYS = BUILTIN_ENV_FIELDS.filter((field) => field.required).map(
  (field) => field.key,
);

export const OFFICIAL_PLUGINS = [
  {
    id: "ingot-platform",
    packageName: "@ingot/platform-plugin",
    importPath: "@ingot/platform-plugin",
    exportName: "platformPlugin",
    label: "@ingot/platform-plugin（平台控制面）",
    canonicalPrefix: "platform",
    directory: "plugins/platform",
    available: true,
    source: "official",
  },
  {
    id: "ingot-security",
    packageName: "@ingot/security-plugin",
    importPath: "@ingot/security-plugin",
    exportName: "securityPlugin",
    label: "@ingot/security-plugin（安全中心）",
    canonicalPrefix: "security",
    directory: "plugins/security",
    available: true,
    source: "official",
  },
  {
    id: "ingot-org",
    packageName: "@ingot/org-plugin",
    importPath: "@ingot/org-plugin",
    exportName: "orgPlugin",
    label: "@ingot/org-plugin（组织管理）",
    canonicalPrefix: "org",
    directory: "plugins/org",
    available: true,
    source: "official",
  },
  {
    id: "ingot-member",
    packageName: "@ingot/member-plugin",
    importPath: "@ingot/member-plugin",
    exportName: "memberPlugin",
    label: "@ingot/member-plugin（会员管理）",
    canonicalPrefix: "member",
    directory: "plugins/member",
    available: true,
    source: "official",
  },
];

export const DEFAULT_OFFICIAL_PLUGIN_IDS = OFFICIAL_PLUGINS.map((plugin) => plugin.id);

export const DEFAULT_THEME = {
  kind: "default",
  id: "default",
  packageName: "@ingot/admin-core",
  exportName: "defaultAdminTheme",
  label: "defaultAdminTheme（核心默认主题）",
  cssExport: "@ingot/admin-core/style.css",
};

export const CONFIG_VERSION = 1;
export const BODY_LIMIT_BYTES = 1024 * 1024;
export const API_BASE = "/__dev-portal/api";
export const SESSION_HEADER = "x-ingot-scaffold-token";
