import "element-plus/theme-chalk/el-message.css";
import "element-plus/theme-chalk/el-message-box.css";
import "./tokens.css";
import "./el-mapping.css";
import "./dark/tokens.css";
import "./dark/el-css-vars.css";
import "./transition.css";
import "./waves.css";
import "./main.css";
